//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTVRequestASongSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coolect
    {
        public int ID { get; set; }
        public string SongName { get; set; }
        public int SongId { get; set; }
        public string NetWorkSite { get; set; }
        public string LocalitySite { get; set; }
        public string author { get; set; }
        public string BackImage { get; set; }
        public string UserName { get; set; }
    }
}
